### ISSUE TITLE
Add Android support

### ISSUE THREAD

**Issue by longmoon77** [M-Reimer/savescreenshot#27]
Browser: Firefox Nightly for Android
Version: Nightly 201008 05:03
Screenshot download failed.
![Screenshot_2020-10-08-22-44-39-374_org.mozilla.fenix.jpg](https://user-images.githubusercontent.com/62339707/95497882-99537680-09d5-11eb-91a2-cafe44dbdee0.jpg)
Website URL: 
[https://zh.m.wikipedia.org/wiki/User:%E6%9C%88%E6%A2%A6%E6%92%AD%E5%AE%A2%E6%A5%BC%E7%8C%AB](https://zh.m.wikipedia.org/wiki/User:%E6%9C%88%E6%A2%A6%E6%92%AD%E5%AE%A2%E6%A5%BC%E7%8C%AB)
From @FirefoxPreview:
![Screenshot_2020-10-09-02-19-28-468_com.twitter.android.jpg](https://user-images.githubusercontent.com/62339707/95498071-e0416c00-09d5-11eb-80ec-ddd45550549a.jpg)

**Comment by M-Reimer** [comment]
There is no Android support in this Add-on and there never was.
It may be a good idea to try porting it, but especially with the new way of installing Add-ons it get even more difficult to develop for Android, so I think I'll delay this until official installation on the stable Firefox for Android gets possible.

**Comment by andreicristianpetcu** [comment]
It works on Android but only for full page jpeg and sites with alphanumeric title.

The workflow on Android is super simple. You install android developer tools, web-ext and connect the phone over USB.

`web-ext run -s savescreenshot -t firefox-android --android-device=b0254ffd --firefox-apk=org.mozilla.fenix`

Any change will be re-deployed on save.

https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/

**Comment by andreicristianpetcu** [comment]
@M-Reimer would you accept a pr that fixes the issue for the mentioned site and hides unsupported features on android?

**Comment by M-Reimer** [comment]
This is the way how I planned to fix it anyway so I if you would create a PR, I would have a look at it and either accept it directly or add some comments about things I would change.

I want to have Android support for most of my Add-ons but delayed this as Mozilla decided for this really bad move with a whitelist of allowed Add-ons.

**Comment by andreicristianpetcu** [comment]
Mozilla is whitelisting because there are unimplemented APIs or APIs that are broken. They want to offer high quality for most users while still giving flexibility with collections for power users. I think it's a good balance. I would have done the same as they.

The web-ext workflow is for devs and live reload, not for average users. Fun thing: I can't debug content extension scripts. Not sure where the issue is.

**Comment by lomomcat** [comment]
And I will meet crash when image file is big.
```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1788924 bytes
	at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:1094)
	at android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.java:1075)
	at mozilla.components.support.utils.Browsers$Companion.findResolvers(Browsers.kt:27)
	at mozilla.components.feature.downloads.DownloadsFeature.getDownloaderApps$feature_downloads_release(DownloadsFeature.kt:18)
	at mozilla.components.feature.downloads.DownloadsFeature.processDownload$feature_downloads_release(DownloadsFeature.kt:3)
	at mozilla.components.feature.downloads.DownloadsFeature$start$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:4)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:7)
	at mozilla.components.feature.downloads.DownloadsFeature$start$2$invokeSuspend$$inlined$mapNotNull$1$2.emit(Collect.kt:4)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:11)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7591)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
Caused by: android.os.TransactionTooLargeException: data parcel size 1788924 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:511)
	at android.content.pm.IPackageManager$Stub$Proxy.queryIntentActivities(IPackageManager.java:6123)
	at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:1084)
	... 18 more
```

**Comment by lomomcat** [comment]
If you could join support for Android, I would be very grateful.
Thanks so much. We Android users desperately need you.

**Comment by M-Reimer** [comment]
Works with version 10 which is available now.
You have to use "Firefox Nightly" and follow my instructions on the AMO page to get it installed.
After doing so please uninstall the "regular" Firefox to remove one active installation from Mozilla's statistics.
